/**
 * Audit entry model (Phase 0.6).
 *
 * Deliberately generic: a small set of fields that later phases (runtime,
 * permissions, approvals, verification) reuse without needing a large
 * event taxonomy now. Event type is a free-form namespaced string
 * (e.g. "tool.invoke", "approval.decided") constrained only to non-empty.
 */

/** Coarse result classification for any audited operation. */
export type AuditStatus = "success" | "failure" | "denied" | "pending";

export interface AuditEntry {
  /** Unique event id (UUIDv7-style time-ordered id generated by the writer). */
  id: string;
  /** ISO-8601 UTC timestamp. */
  timestamp: string;
  /** Namespaced event type, e.g. "tool.invoke", "permission.check". */
  type: string;
  /** Who/what performed the action: "operator", "agent", "system", … */
  actor: string;
  /** Action/tool/operation identifier, e.g. "reviews.reply.publish". */
  action: string;
  /** Outcome classification. */
  status: AuditStatus;
  /** Optional structured metadata; sanitized (secrets redacted) before write. */
  metadata?: Record<string, unknown>;
}

/** Input shape for appendAuditEntry: writer fills id + timestamp. */
export type NewAuditEntry = Omit<AuditEntry, "id" | "timestamp"> & {
  /** Allow caller to pin timestamp (tests, replays). Defaults to now. */
  timestamp?: string;
};
